---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-merge-conflict
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-xml
          - id: check-added-large-files
          - id: check-ast
          - id: check-json

    - repo: https://github.com/psf/black
      rev: 23.10.1
      hooks:
        - id: black
          args: ["--line-length=99", "--experimental-string-processing"]

    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
        - id: flake8
          args: ["--ignore=E501,W503"] # ignore too long line and line break before binary operator,
                                       # black checks it
